FROM python:3.9-slim-buster

RUN pip install -U --no-cache-dir \
        pip \
        quart==0.16.1 \
        quart-cors==0.5.0\
        flask_api==3.0.post1 \
        pymongo[srv]==4.0.1 \
        simple_bcrypt==0.1.0 \
        google-api-python-client>=2.0.2 \
        google-auth-httplib2>=0.1.0 \
        google-auth-oauthlib>=0.4.3

ARG arg_port

EXPOSE $arg_port

ENV HOST=0.0.0.0
ENV PORT=$arg_port

WORKDIR /credentials
COPY credentials .

WORKDIR /src
COPY src .

CMD ["python", "."]
