FROM python:3.9-slim-buster

RUN pip install -U --no-cache-dir \
        pip \
        pymongo[srv]==4.0.1

ARG arg_port

EXPOSE $arg_port

ENV HOST=0.0.0.0
ENV PORT=$arg_port

WORKDIR /src
COPY src .

CMD ["python", "."]
