# build environment
FROM node:slim as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
# COPY package-lock.json ./ # idem
RUN npm ci
RUN npm install react-scripts@3.4.1 -g
COPY . ./
RUN npm run build

# production environment
FROM python:3.9-alpine
ARG arg_port
WORKDIR /app
COPY --from=build /app/build .
EXPOSE $arg_port
CMD ["python", "-m", "http.server", "5000"]
