version: "3.7"

services:
    front:
        build:
            context: .
            args:
                arg_port: 3000
        ports:
            - "8000:3000"
        # volumes:
        #     - "./:./"
        tty: true # bind console
