FROM python:3.9-slim-buster

RUN pip install -U --no-cache-dir \
        pip \
        quart==0.16.1 \
        flask_api==3.0.post1 \
        pymongo[srv]==4.0.1 \
        simple_bcrypt==0.1.0

ARG arg_port

EXPOSE $arg_port

ENV HOST=0.0.0.0
ENV PORT=$arg_port

WORKDIR /src
COPY src .

CMD ["python", "."]
